// export { default as swordsImg } from './crossed-swords.svg'
// export { default as galaxyShadowImg } from './galaxy-color-shadow.svg'
// export { default as shieldImg } from './shield.svg'
//export { default as bot } from './src/img/bot.png'
export { default as galaxyShadowPng } from './galaxy-color-shadow.png'
